apiVersion: v1
data:
  apiToken: ZHQwYzAxLkVVUFBHTElCRUlOV0RBTTZUNUgyQkhCSS5MWEFQWERGV09TSzNIUFJFNVpKN0pPUTdZUTU0SkJNU0pSUFpOUjJQM1hDMkhSNlhFWFBPNFRYQ0Y2RkNLSFdI
  dataIngestToken: ZHQwYzAxLldORFNFRk5BVENNVjYzVVZLVTdaN0FJSS5NR0tCNVVaSlZDNExHTDZCNkpaU1NRR0dQT1lSV1RTWktFN0pNTlBLUlhDRUhHV1NXNEpTWDRZM1laR0pNM1NS
kind: Secret
metadata:
  name: demo-sit-cluster
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: demo-sit-cluster
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://zcn50477.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring: {}
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - debugging
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
    logMonitoring:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-logmodule
        tag: 1.331.39.20260206-150338
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
