apiVersion: v1
data:
  apiToken: ZHQwYzAxLjY0Uk5SNDNHNlRER0g0NTRDQVJUMk9IQi5CWUVKRjJLSEVRQ0pHQVpaRFNTQkVGU0JOU1dDM1RORE42NkxKUlhaQkpSWkVXRURSSVZTRkRPVlozV0M1Q0lT
  dataIngestToken: ZHQwYzAxLkxEVU9MWlFMWjVNVzRJU1ZaQzVaTEdXTy5ONUVGSkdCTk02RldIVzQ3SDNIWkhPWUdDNlVMTUZKRVdTM1k1RE1ZQ1hNT0lNQVdZTVJDVlBPNkFWU09BUUZM
kind: Secret
metadata:
  name: develop
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: develop
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://zcn50477.live.dynatrace.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring: {}
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - debugging
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
    logMonitoring:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-logmodule
        tag: 1.329.73.20260123-140641
  logMonitoring: {}
  telemetryIngest:
    protocols:
      - jaeger
      - otlp
      - statsd
      - zipkin
    serviceName: telemetry-ingest
