name: "Deploy easyTrade App"

on:
  push:
    branches: [ develop ]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name gerard-dev-cluster

      - name: Setup Namespace
        run: |
          # Create namespace only if it doesn't exist to avoid errors
          kubectl create namespace easytrade --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy easyTrade
        run: |
          # Apply the release manifests specifically to the easytrade namespace
          kubectl -n easytrade apply -f ./kubernetes/sample-app/easytrade/kubernetes-manifests/release

      - name: Check Deployment Status
        run: |
          kubectl get pods -n easytrade
